# Generated by Django 4.2 on 2023-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.PositiveIntegerField(default='')),
                ('Student_Name', models.CharField(default='', max_length=20)),
                ('Period1', models.CharField(default='', max_length=10)),
                ('Period2', models.CharField(default='', max_length=10)),
                ('Period3', models.CharField(default='', max_length=10)),
                ('Period4', models.CharField(default='', max_length=10)),
                ('Period5', models.CharField(default='', max_length=10)),
                ('Period6', models.CharField(default='', max_length=10)),
                ('Period7', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
